### PR TITLE
Fix macroman encoding lookup

### PR DESCRIPTION
**Pull request by theseion**

### CODE REVIEW

**Comment by jbrichau** [comment]
@theseion Hi Max, it seems a lot of files are changed in this PR?

I think it's better to redo against master.

**Comment by jbrichau** [comment]
@theseion Ok, did not know I could that myself :)
After changing against master, only 1 file is changed. I believe that should do it :)

**Comment by theseion** [comment]
I've made the same change but this time to Squeak5-Core, Squeak6-Core, and Pharo7-Core.

As for Pharo20-Core, that indeed isn't being loaded in Squeak but is in Pharo 7. I had made the change in a text editor and hadn't realised that there were multiple implementations in different packages.

**Comment by theseion** [comment]
Arrgh! Looks like I accidentally committed metadataless, which breaks the Pharo3 build 😠

**Comment by theseion** [comment]
Ok, this works now.

**Comment by jbrichau** [comment]
Looks good! Thanks!

**Pull request merged**
