### PR TITLE
added GRDynamicVariable

### PR DESCRIPTION
**Pull request by theseion**
* added GRDynamicVariable
* added tests for GRDynamicVariable

### CODE REVIEW

**Comment by jbrichau** [comment]
Hey Max,

As mentioned, thanks for doing this. This is much appreciated.
I notice the tests for Squeak and Gemstone are failing. Should they be working or is this not yet implemented for those platforms?

**Comment by theseion** [comment]
I've only implemented the change for Pharo so far as I wasn't sure wether what I have done fits the way Grease and Seaside play together on the different platforms. If you think the change is fine I'll happily contribute the change for Squeak. I don't have access to / experience with Gemstone, so I'd be glad if somebody else could make the change for Gemstone. I do have access to VW and VASt so I could try to make those changes myself.

**Comment by jbrichau** [comment]
Hi Max,

I took a look at the changes and created a different branch so I can fix the merge issues and take a look at the gemstone stuff. I propose to close this pull request and continue development on that branch together. What do you think?

https://github.com/SeasideSt/Grease/tree/pull23_dev

**Comment by theseion** [comment]
Sure, let's do that.

**Pull request closed without merging**
