### PR TITLE
Add Squeak6 (current trunk)

### PR DESCRIPTION
**Pull request by krono**

### CODE REVIEW

**Comment by krono** [comment]
accompanying Configuration that reditects 6 to here is attached (rename zip -> mcz)
[ConfigurationOfGrease-topa.349.zip](https://github.com/SeasideSt/Grease/files/1453612/ConfigurationOfGrease-topa.349.zip)

**Comment by krono** [comment]
It turns out that those tests only fail on linux but pass on macOS.

I added that in #59

**Comment by jbrichau** [comment]
Hi @krono,

Since issue #14, we have adopted the strategy to create separate packages per platform version. If we load the same packages in different platform versions, there is more work to support and understand where somethings needs to be fixed to deal with platform differences than fixing a bug across all supported platforms.

So, if we want to add Squeak 6, the best thing to do is to add a separate package for it. It would be great if this can be part of this PR. 

I'm fine with merging this into master and I can make sure dev branch catches up.

**Comment by krono** [comment]
Hi @jbrichau 

Done :)

**Comment by jbrichau** [comment]
Hi @krono,
Thanks! I notice quite some tests are failing in Squeak-trunk? If we merge this in, will these be picked up later on when Squeak 6 stabilizes?

**Comment by krono** [comment]
I think so, yes. I'll have a look later-on

**Comment by krono** [comment]
Just a heads up: Most problems here exists because the pre-loaded Metacello in the Trunk-image used by smalltalkCI does not yet support squeak-Trunk. Trackin here: https://github.com/hpi-swa/smalltalkCI/issues/340

**Comment by jbrichau** [comment]
Does using `#useLatestMetacello : true` not fix that?

**Comment by krono** [comment]
You might be right. I was not paying attention, sorry

**Comment by jbrichau** [comment]
No problem, I'm adding that to the `.smalltalk.ston` file now as I also add Pharo7 loading support.

**Comment by krono** [comment]
👍

**Comment by jbrichau** [comment]
All is green for squeak trunk 👍

**Comment by krono** [comment]
Thats good and odd at the same time. On my machine I had one failure still, but I'm glad thats not the case on travis :)

**Comment by jbrichau** [comment]
Which one? I want to make sure it runs on Travis at all.

**Comment by krono** [comment]
Dynamic Var default value. But it just might have been a fluke, I botched the loading and loaded the packages manually

**Pull request merged**
