### PR TITLE
Fix Pharo 12 deprecations

### PR DESCRIPTION
**Pull request by theseion**
- add specific packages for Pharo 12 (copied older versions)
- fix deprecations specific to Pharo 12
- add new methods to platforms  (for tests only)

Not sure about the new selectors. I would have put them in a test only package but there was none. We could create these methods as extensions by creating platform specific test packages.

This PR will fix test failures in Pharo 12 in #161.

### CODE REVIEW

**Comment by jbrichau** [comment]
@theseion The Pharo12 build is an accepted failure. Since it's a moving target, it's ran as an experimental job only. You should be able to merge the PR without further issues. 

But cool to already have some pharo12 issues addressed! Thanks! I'll review then later. Currently off for the week ;-)

**Comment by theseion** [comment]
Done. As I wrote above, I'm not sure about the new methods on `GRPlatform`.

**Comment by jbrichau** [comment]
In the meantime, I had been doing some pair programming with Noury at a Pharo sprint to rework the Slime rule tests in Pharo 12 in https://github.com/SeasideSt/Grease/pull/164

I will need selectively redo some of the changes in this PR

**Comment by jbrichau** [comment]
Changes in this PR have been addressed in the following other PRs that focused on the Slime rules code:
- https://github.com/SeasideSt/Grease/pull/167
- https://github.com/SeasideSt/Grease/pull/164

I have now also addressed the sends of deprecated messages that remained in https://github.com/SeasideSt/Grease/pull/172

The additions that were made to Grease-Core related to creating test classes for the Slime tests. Since this is now Pharo-only code anyway, I do not think we should add them to the Core (and create implementations for all supported platforms for them).
Therefore, I propose to close this PR.

**Pull request closed without merging**
