### PR TITLE
File utilities for streaming uploads

### PR DESCRIPTION
**Pull request by theseion**
This PR accompanies https://github.com/SeasideSt/Seaside/pull/1196.

### CODE REVIEW

**Comment by theseion** [comment]
The one failure is due to an unexpected pass. This should be fixed in a separate PR.

**Comment by theseion** [comment]
This PR also deals with the issue discussed in #1159. This might not be the best solution.

**Comment by jbrichau** [comment]
Hi @theseion !
Thanks for picking this one up again.

I wonder if it would not be easier (and keep the codebase more succint) to write `binaryWriteStreamOn:do:`  in terms of the existing `writeFileStreamOn: aString do: aBlock binary: aBoolean` method? Is it because passing through the filename instead of the filereference does not work for this? The advantage is also we have some tests for the existing methods.

**Comment by theseion** [comment]
You're right, the new method is unnecessary. I've removed it.

**Comment by jbrichau** [comment]
@theseion the unexpected pass is indeed because https://github.com/svenvc/zinc/issues/86 is now fixed in Pharo10. I now removed it in ce61d53225c603881c857766e6c5c29c0fc4b7f5

**Comment by jbrichau** [comment]
I would say we need a test for the new method. 
But I will take care of it before marking a new release and merge this one in for now so we can merge the Seaside PRs

**Comment by theseion** [comment]
Thanks, much appreciated!

**Pull request merged**
