### PR TITLE
Removed GRPackage

### PR DESCRIPTION
**Pull request by theseion**
refs #1077

### CODE REVIEW

**Comment by theseion** [comment]
This PR is related to https://github.com/SeasideSt/Seaside/pull/1100

**Comment by marianopeck** [comment]
Hi max. What was the reason behind this change? Couldn't fine any description anywhere... Thanks

**Comment by jecisc** [comment]
Hi, @marianopeck You can find a thread here: https://github.com/SeasideSt/Seaside/issues/1077

**Comment by marianopeck** [comment]
Ufff we use the GRPackage in seaside for VA Smalltalk. I don't have much
time today but let me give you more details in the coming week. In any
case, I I am not proposing delaying your pushes. Just wanted to explain
what our usage is.

Thanks!

**Comment by jbrichau** [comment]
Hi @marianopeck 
Thanks for chiming in. Are you using GRPackage to track dependencies for loading Seaside?
Overall, the package dependencies for Seaside in GRPackage are in a somewhat abandoned state. It would be good if we can sort out what to leave in and what we can remove (since more-or-less broken anyway)

**Comment by theseion** [comment]
Thanks @marianopeck, we'll wait for your feedback.

**Comment by jbrichau** [comment]
@marianopeck @theseion 

Given this feedback, I propose we do not remove GRPackage from Grease at this time. We might want to make a call for people to report about their usage of GRPackage before actually removing it. 

Concerning the abandoned state of the dependencies (since we use Metacello for package dependencies since a long time), I guess most of the dependencies uphold because the package structure has not changed so much since 3.0. They are still in Seaside 3.3. Now, I do have some vague memory about those dependencies being checked against the ConfigurationOf... so I'll poke around to see if that was an illusion of mine or not ;) (since it may help us exporting dependencies from the baseline to GRPackage dependencies).

**Comment by marianopeck** [comment]
Thank you both for listening. I hope we are able to make a new Seaside port in the middle term so at that time, I would be willing to update the GRPackage dependencies.  Now...I didn't know there was a chance they were actually auto-generated out of Metacello info... if that's true and you find something @jbrichau please let us know!

**Pull request closed without merging**
