### PR TITLE
Support Pharo native Deprecation

### PR DESCRIPTION
**Pull request by marschall**
Implement `#deprecationExceptionSet` for Pharo and add `Deprecation`.

Currently `#deprecationExceptionSet` is empty for Pharo resulting in a nasty stack trace if somebody sends a message that Pharo deprecated, see #179.

DeprecationMissing

Unfortunately this doesn't actually make `Deprecation` work with the Seaside tools as `Deprecation >> #messageText` results in a MNU. This looks like a Pharo bug to me, I filed https://github.com/pharo-project/pharo/issues/16897.

```
UndefinedObject(Object)>>doesNotUnderstand: #homeMethod
Deprecation>>sendingMethodName
[ :str |
		self shouldTransform ifTrue: [
			str nextPutAll:  'Automatic deprecation code rewrite: '].
		str
			nextPutAll: 'The method ';
			nextPutAll: self deprecatedMethodName;
			nextPutAll: ' called from ';
			nextPutAll: self sendingMethodName;
			nextPutAll: ' has been deprecated. ';
		 	nextPutAll: explanationString] in Deprecation>>messageText in Block: [ :str |...
String class(SequenceableCollection class)>>new:streamContents:
String class(SequenceableCollection class)>>streamContents:
Deprecation>>messageText
[ :each | 
		(each messageText = aNotification messageText)
			and: [ each details = aNotification details ] ] in WADeprecatedToolFilter>>deprecated: in Block: [ :each | ...
OrderedCollection>>reject:
WADeprecatedToolFilter>>deprecated:
[ :notification | self deprecated: notification ] in WADeprecatedToolFilter>>handleFiltered: in Block: [ :notification | self deprecated: notification ]
```

### CODE REVIEW

**Comment by marschall** [comment]
No idea why GemStone/S is failing

```
Unhandled Error in script: /home/runner/.smalltalkCI/_builds/repos/GsDevKit_stones/bin/loadTode.stone
---------------------
a MetacelloPackageSpecResolutionError occurred (error 2710), Could not resolve: ConfigurationOfMetacello [ConfigurationOfMetacello] in /home/runner/.smalltalkCI/_builds/stones/smalltalkci/package-cache http://seaside.gemtalksystems.com/ss/metacello
---------------------
1 [] in SuperDoitExecution >> doit @69 line 42  [GsNMethod 111145473]
Could not resolve: ConfigurationOfMetacello [ConfigurationOfMetacello] in /home/runner/.smalltalkCI/_builds/stones/smalltalkci/package-cache http://seaside.gemtalksystems.com/ss/metacello
```

```
Unhandled Error in script: /home/runner/.smalltalkCI/_builds/repos/GsDevKit_stones/bin/loadTode.stone
---------------------
UserDefinedError: can't find EOCD position
---------------------
1 [] in SuperDoitExecution >> doit @41 line 32  [GsNMethod 108265985]
UserDefinedError: can't find EOCD position
2 UserDefinedError (AbstractException) >> _executeHandler: @7 line 11  [GsNMethod 3907329]
3 UserDefinedError (AbstractException) >> _signalWith: @1 line 2  [GsNMethod 3915009]
4 UserDefinedError (AbstractException) >> signal @2 line 47  [GsNMethod 3902977]
5 ZipArchive (Object) >> error: @6 line 7  [GsNMethod 6181633]
6 ZipArchive >> readFrom: @14 line 10  [GsNMethod 29782273]
7 MCMczReader >> zip @5 line 4  [GsNMethod 40344321]
```

**Comment by jbrichau** [comment]
Try running it again. This error means a problem with the squeaksource server on http://seaside.gemtalksystems.com/ss/

Something I promised Dale to take a look at and convert to a plain webserver.... but it became less urgent as the stability had improved. So, just run that build again. It will probably work.

**Comment by jbrichau** [comment]
I re-ran the failed builds and now they pass.

**Review by jbrichau — APPROVED** [review]

**Comment by marschall** [comment]
Thx, Pharo bug is fixed as well.

**Pull request merged**
