### PR TITLE
Make loadable in Pharo 7

### PR DESCRIPTION
**Pull request by StephanEggermont**

### CODE REVIEW

**Comment by StephanEggermont** [comment]
Build failure looks unrelated

**Comment by marschall** [comment]
Since we're now metadataless and #14 as been fixed I wonder whether it would not be better to copy and paste Grease-Pharo60-Core to Grease-Pharo70-Core or Grease-Pharo7-Core.

**Comment by jbrichau** [comment]
I agree with @marschall , we have adopted the strategy to copy/paste the packages per Pharo version. If we load the same packages in the different Pharo versions, there is more work to support and understand where somethings needs to be fixed than fixing a bug across all supported platforms.

**Comment by jbrichau** [comment]
Added Pharo70 package in aa9e29d8e91fa9929d97c472f08ca7ac527fc505

**Comment by jbrichau** [comment]
Fixed this in https://github.com/SeasideSt/Grease/pull/60

**Pull request closed without merging**
